name: Deploy to Instance

env:
    REPO_NAME: ${{ github.event.repository.name }}
    REPO_URL: ${{ github.event.repository.url }}

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build and package the code
              run: |
                  ls -la
                  cd Frontend
                  npm install
                  npm run build
                  cd ../Admin
                  npm install
                  npm run build
                  ls -la

            - name: Connect to AWS Lightsail, extract file and delete the file
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.HOST_IP }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  passphrase: ""
                  port: 22
                  script: |
                      if [ -d /var/www/Asis ]; then
                        cd /var/www/Asis && sudo git pull
                      else
                        sudo git clone https://github.com/Pr3c10us/Asis.git /var/www/Asis
                      fi
                      cd /var/www/Asis/Backend && sudo npm install && if sudo npm stop; then
                        # If command1 succeeds
                        echo "Command 1 succeeded"
                        # Run another command
                        sudo npm start
                      else
                          # If command1 fails
                          echo "Command 1 failed"
                          # Run a different command
                          sudo npm start
                      fi
                      if [ ! -d /var/www/Asis/Frontend/dist ]; then
                        sudo mkdir /var/www/Asis/Frontend/dist
                      fi
                      if [ ! -d /var/www/Asis/Admin/dist ]; then
                        sudo mkdir /var/www/Asis/Admin/dist
                      fi
                      sudo chown -R asis:asis folder

            - name: copy file via ssh password
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.HOST_IP }}
                  username: "root"
                  password: ${{ secrets.SSH_PASSWORD }}
                  source: "Frontend/dist/"
                  target: "/var/www/Asis/Frontend/dist/"
                  rm: true
                  strip_components: 1

            - name: copy file via ssh password
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.HOST_IP }}
                  username: "root"
                  password: ${{ secrets.SSH_PASSWORD }}
                  source: "Admin/dist/"
                  target: "/var/www/Asis/Admin/dist/"
                  strip_components: 1
                  rm: true
