name: Deploy to Instance

env:
  REPO_NAME: ${{ github.event.repository.name }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install sshpass
        run: echo $REPO_NAME

      # - name: Install sshpass
      #   run: sudo apt-get install -y sshpass

      # - name: Clone or pull the repository
      #   run: |
      #     if sshpass -p ${{ secrets.SSH_PASSWORD }} ssh your-username@your-instance-ip-or-hostname '[ -d /var/www/your-repo ]'; then
      #       sshpass -p ${{ secrets.SSH_PASSWORD }} ssh your-username@your-instance-ip-or-hostname "cd /var/www/your-repo && git pull"
      #     else
      #       sshpass -p ${{ secrets.SSH_PASSWORD }} ssh your-username@your-instance-ip-or-hostname "git clone https://github.com/yourusername/your-repo.git /var/www/your-repo"
      #     fi

      # - name: Build Frontend
      #   run: |
      #     sshpass -p ${{ secrets.SSH_PASSWORD }} ssh your-username@your-instance-ip-or-hostname "cd /var/www/your-repo/Frontend && sudo npm install && sudo npm run build"

      # - name: Build Admin
      #   run: |
      #     sshpass -p ${{ secrets.SSH_PASSWORD }} ssh your-username@your-instance-ip-or-hostname "cd /var/www/your-repo/Admin && sudo npm install && sudo npm run build"

      # - name: Stop and Start Backend
      #   run: |
      #     sshpass -p ${{ secrets.SSH_PASSWORD }} ssh your-username@your-instance-ip-or-hostname "cd /var/www/your-repo/Backend && sudo npm stop && sudo npm start"
